---
- name: Install apt sources.list
  template:
    dest: /etc/apt/sources.list
    group: root
    owner: root
    mode: 0644
    src: sources.list.j2
  notify: Update repositories cache
  tags:
    - apt_sources

- name: Set default release
  copy:
    content: 'Apt::default-Release "{{ apt_sources_default_release }}";'
    dest: /etc/apt/apt.conf.d/10defaultrelease
    group: root
    owner: root
    mode: 0644
  when: apt_sources_default_release is defined
  tags:
    - apt_sources

